# Generated by Django 2.1.5 on 2019-01-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190113_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instauser', models.CharField(max_length=100)),
                ('instapass', models.CharField(max_length=100)),
            ],
        ),
    ]
