# Generated by Django 2.1.5 on 2019-01-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='user',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
