# Generated by Django 2.1.5 on 2019-04-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190403_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feautured',
            field=models.BooleanField(default=False),
        ),
    ]
